import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :vibeflow, VibeflowWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Vibeflow.Finch

config :vibeflow, VibeflowWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# NOTE: This app is deployed with `mix phx.server` (see `Procfile`), which does
# not automatically load `config/runtime.exs` (unlike Elixir releases). Import
# it here so production picks up runtime env-based configuration (e.g. Brevo).
import_config "runtime.exs"
